
name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /var/www/dataads
            git pull

            # --- frontend ---
            cd frontend
            npm install
            npm run build

            # --- backend ---
            cd /var/www/dataads/backend
            source .venv/bin/activate
            pip install -r requirements.txt
            deactivate

            # --- restart services ---
            sudo systemctl restart dataads-backend
            sudo systemctl reload nginx
